name: Build DDist

on:
  push:
    tags: ["v*"]

env:
  ARTIFACTS_DIRECTORY: "${{github.workspace}}/.artifacts"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
    - run: |
        python -m pip -r requirements-windows.txt
        python -m pip install .
        python -m pip install pyinstaller

    - name: Build executable
      run: make build-win

    - name: create innosetup installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: ddist_installer.iss
        options: /O+ /DMyAppVersion=${{ github.ref_name }}

    - uses: actions/upload-artifact@v4
      with:
        name: ddist-setup-${{ github.ref_name }}.exe
        path: build/ddist/ddist.exe
